/** Current Go OpenAPI -> Kimi Admin DTO boundary. No page imports generated data. */
import {
  getCustomer, getCustomerActivityAnalytics, getCustomerContext, listCustomerChatActivity, listCustomerEvents, listCustomerSurveyAnswers,
  getLegacyAttachment, getLegacyChannel, getLegacyCoupon, getLegacyCouponShare, getLegacyImage, getLegacyImageFacets,
  getLegacyMiniProgram, getLegacyOrder, getLegacyOrderItems, getLegacyQuestionnaire, getLegacyQuestionnaireResults,
  getLegacyWecomTag, getLegacyWecomTagExecutionGate, getLegacyWecomTagGroup, getProduct,
  getServicePeriodMemberGridAccess, getServicePeriodMemberGridSchema, getServicePeriodMemberGridShareSettings,
  getServicePeriodProduct, getSurveyOperations, getSurveyOperationsPageData, getSurveySafeSubmissionAnalysis,
  listCustomers, listLegacyAttachments, listLegacyChannelEntrants, listLegacyChannels, listLegacyCouponClaims,
  listLegacyCouponProductOptions, listLegacyCoupons, getLegacyImageList, listLegacyMiniPrograms, listLegacyOrders, listLegacyRefunds, listLegacyWechatOrderExternalEffects,
  listLegacyQuestionnaireSubmissions, listLegacyQuestionnaires, listLegacyWecomTagGroups, listLegacyWecomTags,
  listProductLocalEntitlements, listProducts, listServicePeriodMemberViews, listServicePeriodMembers,
  listServicePeriodProducts, listSurveyQuestionnaireExternalPushLogs,
  activateAIAudiencePackage, archiveLegacyWecomTag, archiveLegacyWecomTagGroup, archiveAIAudiencePackage, copyAIAudiencePackage, createAIAudiencePackageGroup, createLegacyWecomTag, createLegacyWecomTagGroup, deleteAIAudiencePackageGroup, disableRadarLink, enableRadarLink, getAIAudiencePackage, getRadarLink, listAIAudiencePackageGroups, listAIAudiencePackages, listRadarLinkEvents, listRadarLinks, pauseAIAudiencePackage, queueLegacyWecomTagSync, updateAIAudiencePackageGroup, updateLegacyWecomTagGroupPatch, updateLegacyWecomTagPatch, type Customer as ApiCustomer, type LegacyChannelListItem, type LegacyQuestionnaire, type RadarLink as ApiRadarLink,
} from './generated/health';
import type { AdminDb, AttachItem, Channel, Coupon, Customer, ImageItem, MpItem, Order, Product, Questionnaire, SpProduct, TagGroup, Tone, WecomTag } from '../shared/api/types';
import { apiRequestOptions, unwrapGenerated } from './transport';

type Obj = Record<string, unknown>;
const obj = (value: unknown): Obj => value && typeof value === 'object' ? value as Obj : {};
const text = (value: unknown, fallback = '—'): string => value == null || value === '' ? fallback : String(value);
const list = (value: unknown, ...keys: string[]): unknown[] => { const source = obj(value); for (const key of keys) if (Array.isArray(source[key])) return source[key] as unknown[]; return []; };
const toneFor = (status: unknown): Tone => { const value = text(status, '').toLowerCase(); if (/active|enabled|paid|success|completed|published/.test(value)) return 'ok'; if (/pending|draft|processing/.test(value)) return 'warn'; if (/disabled|archived|failed|cancel|closed/.test(value)) return 'gray'; return 'blue'; };
const call = async <T>(request: Promise<T>): Promise<unknown> => unwrapGenerated(await request as { status: number; data: unknown }) as unknown;

export function customerPageDto(customer: ApiCustomer): Customer { return { id: String(customer.id), name: customer.name, owner: customer.owner_staff_id == null ? '未分配' : String(customer.owner_staff_id), mobile: '—' }; }
export function questionnairePageDto(questionnaire: LegacyQuestionnaire): Questionnaire { return { resourceId: questionnaire.id, name: questionnaire.title, assess: questionnaire.assessment_enabled, off: questionnaire.is_disabled, action: questionnaire.status, created: questionnaire.created_at, count: String(questionnaire.submission_count) }; }
export function channelPageDto(channel: LegacyChannelListItem): Channel { return { resourceId: channel.id, name: channel.channel_name, code: channel.channel_code, type: '渠道码', status: channel.status, tone: toneFor(channel.status), mat: '—', tag: '—', tagTone: 'gray', users: String(channel.channel_contact_count), qr: '后端未返回二维码地址' }; }
export const orderPageDto = (value: unknown): Order => { const x = obj(value); return { time: text(x.created_at), no: text(x.merchant_order_no, text(x.order_no)), plat: text(x.provider_label, text(x.provider)), payer: text(x.payer_name), uid: text(x.payer_id), product: text(x.product_name), amount: text(x.amount), status: text(x.status_label, text(x.status)), tone: toneFor(x.status), pay: text(x.currency) }; };
export const productPageDto = (value: unknown): Product => { const x = obj(value); return { code: text(x.id), name: text(x.name), price: text(x.price), status: text(x.status), tone: toneFor(x.status), sold: text(x.sold_count, '0'), updated: text(x.updated_at) }; };
export const serviceProductPageDto = (value: unknown): SpProduct => { const x = obj(value); return { code: text(x.id), name: text(x.name), price: text(x.price), status: text(x.status), tone: toneFor(x.status), sold: text(x.member_count, '0'), updated: text(x.updated_at) }; };
export const couponPageDto = (value: unknown): Coupon => { const x = obj(value); return { resourceId: Number(x.id), name: text(x.name), code: text(x.code), off: text(x.discount_label, text(x.discount)), scope: text(x.scope), window: text(x.valid_window), issue: text(x.issue_count, '0'), status: text(x.status), tone: toneFor(x.status) }; };
export const imagePageDto = (value: unknown): ImageItem => { const x = obj(value); return { name: text(x.name, text(x.filename)), size: text(x.size), tag: text(x.category), tone: toneFor(x.status), bg: '#EFF4FF', desc: text(x.description, ''), tags: text(x.tags, ''), enabled: x.enabled !== false, uploadedAt: text(x.created_at) }; };
export const miniProgramPageDto = (value: unknown): MpItem => { const x = obj(value); return { name: text(x.name), appid: text(x.appid), pagepath: text(x.pagepath), cardTitle: text(x.title), thumbStatus: text(x.thumbnail_status), thumbOk: x.thumbnail_status === 'ready', enabled: x.enabled !== false, bg: '#EFF4FF' }; };
export const attachmentPageDto = (value: unknown): AttachItem => { const x = obj(value); return { name: text(x.name, text(x.filename)), type: text(x.content_type), size: text(x.size), tags: text(x.tags, ''), uploadedAt: text(x.created_at), enabled: x.enabled !== false }; };
export const tagGroupPageDto = (value: unknown): TagGroup => { const x = obj(value); return { id: Number(x.id), name: text(x.name) }; };
export const tagPageDto = (value: unknown): WecomTag => { const x = obj(value); return { id: Number(x.id), groupId: Number(x.group_id), name: text(x.name), users: Number(x.user_count || 0), syncedAt: text(x.updated_at) }; };
export const radarPageDto = (link: ApiRadarLink): AdminDb['radarLinks'][number] => ({ id: link.link_id, title: link.title, target_type: link.attachment_id ? 'pdf' : link.cover_image_id ? 'image' : 'link', original_url: link.destination_url, file_name_snapshot: '', media_item_id: String(link.attachment_id || link.cover_image_id || ''), enabled: link.status === 'enabled', auth_required: true, staff_id: String(link.created_by), code: link.public_code, total_landings: 0, authorized_users: 0, view_count: 0, last_viewed_at: link.updated_at });
export const audienceGroupPageDto = (value: unknown): AdminDb['audienceGroups'][number] => ({ id: Number(obj(value).group_id), name: text(obj(value).name) });
export const audiencePackagePageDto = (value: unknown): AdminDb['audiencePackages'][number] => { const x = obj(value); return { id: Number(x.package_id), name: text(x.name), groupId: Number(x.group_id || 0), count: Number(x.member_count || 0), lastRefresh: text(x.refreshed_at), refreshMode: text(x.refresh_mode), running: x.lifecycle === 'active', version: 'v' + text(x.version), definition: '', incremental: 'off', daily: 'off', boundAutomation: '' }; };
export async function setRadarEnabled(linkId: number, enabled: boolean): Promise<void> { const current = obj(await call(getRadarLink(linkId, apiRequestOptions()))).link as ApiRadarLink; const request = { expected_version: current.version }; await call(enabled ? enableRadarLink(linkId, request, apiRequestOptions()) : disableRadarLink(linkId, request, apiRequestOptions())); }
export async function readRadarEvents(linkId: number): Promise<AdminDb['radarEvents']> { const page = await call(listRadarLinkEvents(linkId, undefined, apiRequestOptions())); return list(page, 'items').map((item) => ({ unionid_masked: text(obj(item).unionid_masked), external_userid: text(obj(item).external_userid), created_at: text(obj(item).occurred_at, text(obj(item).created_at)) })); }
async function audiencePackageVersion(packageId: number): Promise<number> { return Number(obj(obj(await call(getAIAudiencePackage(packageId, apiRequestOptions()))).package).version); }
export async function saveAudienceGroup(input: { id?: number; name: string }): Promise<AdminDb['audienceGroups'][number]> {
  const opt = apiRequestOptions();
  if (input.id == null) {
    const result = obj(await call(createAIAudiencePackageGroup({ name: input.name, expected_version: 0 }, opt)));
    return audienceGroupPageDto(result.group);
  }
  const groups = await call(listAIAudiencePackageGroups(opt));
  const existing = list(groups, 'items').map(obj).find((item) => Number(item.group_id) === input.id);
  if (!existing) throw new Error('标签组不存在或已被删除');
  const result = obj(await call(updateAIAudiencePackageGroup(input.id, { name: input.name, expected_version: Number(existing.version) }, opt)));
  return audienceGroupPageDto(result.group);
}
export async function deleteAudienceGroup(groupId: number): Promise<void> { const groups = await call(listAIAudiencePackageGroups(apiRequestOptions())); const existing = list(groups, 'items').map(obj).find((item) => Number(item.group_id) === groupId); if (!existing) throw new Error('标签组不存在或已被删除'); await call(deleteAIAudiencePackageGroup(groupId, { expected_version: Number(existing.version) }, apiRequestOptions())); }
export async function setAudiencePackageRunning(packageId: number, running: boolean): Promise<void> { const expected_version = await audiencePackageVersion(packageId); await call(running ? activateAIAudiencePackage(packageId, { expected_version }, apiRequestOptions()) : pauseAIAudiencePackage(packageId, { expected_version }, apiRequestOptions())); }
export async function copyAudiencePackageDto(packageId: number): Promise<AdminDb['audiencePackages'][number]> { const expected_version = await audiencePackageVersion(packageId); const result = obj(await call(copyAIAudiencePackage(packageId, { expected_version }, apiRequestOptions()))); return audiencePackagePageDto(result.package); }
export async function archiveAudiencePackage(packageId: number): Promise<void> { const expected_version = await audiencePackageVersion(packageId); await call(archiveAIAudiencePackage(packageId, { expected_version }, apiRequestOptions())); }
const writeMeta = () => ({ idempotency_key: globalThis.crypto?.randomUUID?.() || `web-${Date.now()}` });
export async function saveTagGroupDto(input: { id?: number; name: string; firstTag?: string }): Promise<TagGroup> { const opt = apiRequestOptions(); if (input.id == null) { if (!input.firstTag) throw new Error('新建标签组必须提供首个标签'); const result = obj(await call(createLegacyWecomTagGroup({ group_name: input.name, first_tag_name: input.firstTag, ...writeMeta() }, opt))); return tagGroupPageDto(result.group); } const result = obj(await call(updateLegacyWecomTagGroupPatch(input.id, { group_name: input.name, ...writeMeta() }, opt))); return tagGroupPageDto(result.group); }
export async function saveTagDto(input: { id?: number; groupId: number; name: string }): Promise<WecomTag> { const opt = apiRequestOptions(); if (input.id != null) { const result = obj(await call(updateLegacyWecomTagPatch(input.id, { tag_name: input.name, ...writeMeta() }, opt))); return tagPageDto(result.tag); } const group = obj(await call(getLegacyWecomTagGroup(input.groupId, opt))).group; if (!group) throw new Error('标签组不存在或已被删除'); const result = obj(await call(createLegacyWecomTag({ group_id: input.groupId, group_name: text(obj(group).name), tag_name: input.name, ...writeMeta() }, opt))); return tagPageDto(result.tag); }
export async function archiveTagDto(tagId: number): Promise<void> { await call(archiveLegacyWecomTag(tagId, writeMeta(), apiRequestOptions())); }
export async function queueTagSyncDto(): Promise<unknown> { return call(queueLegacyWecomTagSync(writeMeta(), apiRequestOptions())); }

export function emptyAdminDb(): AdminDb { return { radarLinks: [], radarEvents: [], aiPlans: [], aiRcs: {}, funnelRows: [], funnelViews: [], audienceGroups: [], audiencePackages: [], audienceMembers: {}, audienceSenders: {}, audienceRecords: {}, cycleTasks: [], cycleRuns: {}, qOps: {}, tagGroups: [], wecomTags: [], couponClaims: {}, configCategories: [], staff: [], groupChats: [], rows: { customers: [], tags: [], qa: [], msgs: [], qStats: [], questionnaires: [], qSubs: [], qApply: [], edTools: [], edQs: [], edAssignees: [], chStats: [], channels: [], orders: [], orderKv: [], orderEvents: [], spProducts: [], products: [], coupons: [], images: [], mpItems: [], attachItems: [], agents: [], agentSlots: [], agentDeps: [] } }; }
export interface AdminReadContext { page?: string; id?: string }

/** Shared lists are loaded from current operations only. A rejected request reaches the page error state. */
export async function readAdminRows(page?: string): Promise<AdminDb> {
  const opt = apiRequestOptions();
  const needs = (...screens: string[]) => !page || screens.includes(page);
  const skip = Promise.resolve({});
  const responses = await Promise.all([
    needs('customers', 'customerDetail') ? call(listCustomers({ limit: 50 }, opt)) : skip,
    needs('questionnaires', 'questionnaireDetail', 'questionnaireOps') ? call(listLegacyQuestionnaires({ limit: 50, offset: 0 }, opt)) : skip,
    needs('channels', 'channelForm', 'questionnaireOps', 'productForm', 'spProductForm') ? call(listLegacyChannels({ limit: 50, include_archived: true }, opt)) : skip,
    needs('orders', 'orderDetail') ? call(listLegacyOrders(undefined, opt)) : skip,
    needs('products', 'productForm') ? call(listProducts(undefined, opt)) : skip,
    needs('spProducts', 'spProductForm', 'spProductData') ? call(listServicePeriodProducts(undefined, opt)) : skip,
    needs('coupons', 'couponForm', 'couponData') ? call(listLegacyCoupons(undefined, opt)) : skip,
    needs('images') ? call(getLegacyImageList(undefined, opt)) : skip,
    needs('attach') ? call(listLegacyAttachments(undefined, opt)) : skip,
    needs('mpLib') ? call(listLegacyMiniPrograms(undefined, opt)) : skip,
    needs('tags') ? call(listLegacyWecomTagGroups(opt)) : skip,
    needs('tags') ? call(listLegacyWecomTags(opt)) : skip,
    needs('radar', 'radarDetail', 'radarForm') ? call(listRadarLinks(undefined, opt)) : skip,
    needs('automation', 'audienceEdit') ? call(listAIAudiencePackageGroups(opt)) : skip,
    needs('automation', 'audienceEdit') ? call(listAIAudiencePackages(undefined, opt)) : skip,
  ]);
  const [customers, questionnaires, channels, orders, products, spProducts, coupons, images, attachments, minis, tagGroups, tags, radar, audienceGroups, audiencePackages] = responses; const db = emptyAdminDb();
  db.rows.customers = list(customers, 'items').map((x) => customerPageDto(x as ApiCustomer)); db.rows.questionnaires = list(questionnaires, 'items', 'questionnaires').map((x) => questionnairePageDto(x as LegacyQuestionnaire)); db.rows.channels = list(channels, 'channels', 'items').map((x) => channelPageDto(x as LegacyChannelListItem)); db.rows.orders = list(orders, 'items', 'orders').map(orderPageDto); db.rows.products = list(products, 'items').map(productPageDto); db.rows.spProducts = list(spProducts, 'items').map(serviceProductPageDto); db.rows.coupons = list(coupons, 'items', 'coupons').map(couponPageDto); db.rows.images = list(images, 'items', 'images').map(imagePageDto); db.rows.attachItems = list(attachments, 'items', 'attachments').map(attachmentPageDto); db.rows.mpItems = list(minis, 'items', 'mini_programs').map(miniProgramPageDto); db.tagGroups = list(tagGroups, 'items', 'groups').map(tagGroupPageDto); db.wecomTags = list(tags, 'items', 'tags').map(tagPageDto); db.radarLinks = list(radar, 'items').map((x) => radarPageDto(x as ApiRadarLink)); db.audienceGroups = list(audienceGroups, 'items', 'groups').map(audienceGroupPageDto); db.audiencePackages = list(audiencePackages, 'items').map(audiencePackagePageDto); return db;
}

/** Detail page reads are deliberately page-scoped and never synthesize demo records. */
export async function readAdminPage(context: AdminReadContext = {}): Promise<AdminDb> {
  const db = await readAdminRows(context.page); const id = context.id || ''; if (!id) return db; const opt = apiRequestOptions(); const numeric = Number(id);
  if (context.page === 'customerDetail') { const [detail, customerContext, events, answers, chat, analytics] = await Promise.all([call(getCustomer(numeric, opt)), call(getCustomerContext(numeric, undefined, opt)), call(listCustomerEvents(numeric, undefined, opt)), call(listCustomerSurveyAnswers(numeric, undefined, opt)), call(listCustomerChatActivity(numeric, undefined, opt)), call(getCustomerActivityAnalytics(numeric, undefined, opt))]); const customer = obj(detail).customer || detail; db.rows.customers = [customerPageDto(customer as ApiCustomer)]; db.rows.tags = list(detail, 'tags').map((x) => ({ name: text(obj(x).name) })); db.rows.qa = list(answers, 'items', 'answers').map((x) => ({ q: text(obj(x).question), a: text(obj(x).answer) })); db.rows.msgs = [...list(events, 'items', 'events').map((x) => ({ who: text(obj(x).actor_name), time: text(obj(x).created_at), text: text(obj(x).type), me: false })), ...list(chat, 'items', 'messages').map((x) => ({ who: text(obj(x).sender_name), time: text(obj(x).created_at), text: text(obj(x).content), me: obj(x).is_staff === true }))]; db.rows.qStats = list(analytics, 'items', 'stats').map((x) => ({ label: text(obj(x).label), value: text(obj(x).value), unit: text(obj(x).unit, '') })); void customerContext; }
  if (context.page === 'questionnaireDetail' || context.page === 'questionnaireOps') { const [detail, results, submissions, analysis, operations, pageData, logs] = await Promise.all([call(getLegacyQuestionnaire(numeric, opt)), call(getLegacyQuestionnaireResults(numeric, opt)), call(listLegacyQuestionnaireSubmissions(numeric, undefined, opt)), call(getSurveySafeSubmissionAnalysis(numeric, undefined, opt)), call(getSurveyOperations(numeric, opt)), call(getSurveyOperationsPageData(numeric, opt)), call(listSurveyQuestionnaireExternalPushLogs(numeric, undefined, opt))]); const q = obj(detail).questionnaire || detail; db.rows.questionnaires = [questionnairePageDto(q as LegacyQuestionnaire)]; db.rows.qSubs = list(submissions, 'items', 'submissions').map((x) => ({ time: text(obj(x).submitted_at), uid: text(obj(x).customer_id), by: text(obj(x).customer_name), score: text(obj(x).score), tags: list(obj(x).tags).map(String) })); db.rows.qApply = list(logs, 'items', 'logs').map((x) => ({ time: text(obj(x).created_at), sid: text(obj(x).submission_id), uid: text(obj(x).external_userid), status: text(obj(x).status), tone: toneFor(obj(x).status), err: text(obj(x).error, '') })); void results; void analysis; void operations; void pageData; }
  if (context.page === 'channelForm') { const [detail, entrants] = await Promise.all([call(getLegacyChannel(numeric, opt)), call(listLegacyChannelEntrants(numeric, undefined, opt))]); db.rows.channels = [channelPageDto((obj(detail).channel || detail) as LegacyChannelListItem)]; db.rows.chStats = list(entrants, 'items', 'entrants').map((x) => ({ label: text(obj(x).label), value: text(obj(x).value), unit: text(obj(x).unit, '') })); }
  if (context.page === 'orderDetail') { const [detail, items, refunds, effects] = await Promise.all([call(getLegacyOrder(id, undefined, opt)), call(getLegacyOrderItems(id, undefined, opt)), call(listLegacyRefunds(undefined, opt)), call(listLegacyWechatOrderExternalEffects(id, opt))]); db.rows.orders = [orderPageDto(obj(detail).order || detail)]; db.rows.orderKv = Object.entries(obj(detail)).map(([k, v]) => ({ k, v: text(v), mono: false })); db.rows.orderEvents = [...list(items, 'items').map((x) => ({ time: text(obj(x).created_at), ev: text(obj(x).name), st: text(obj(x).status), tone: toneFor(obj(x).status) })), ...list(refunds, 'items', 'refunds').map((x) => ({ time: text(obj(x).created_at), ev: '退款 ' + text(obj(x).refund_no), st: text(obj(x).status), tone: toneFor(obj(x).status) })), ...list(effects, 'items', 'effects').map((x) => ({ time: text(obj(x).created_at), ev: '外推回执', st: text(obj(x).status), tone: toneFor(obj(x).status) }))]; }
  if (context.page === 'productForm') { const [detail, entitlements] = await Promise.all([call(getProduct(numeric, opt)), call(listProductLocalEntitlements(numeric, undefined, opt))]); db.rows.products = [productPageDto(detail)]; db.rows.orderKv = list(entitlements, 'items').map((x) => ({ k: text(obj(x).name), v: text(obj(x).status), mono: false })); }
  if (context.page === 'spProductForm' || context.page === 'spProductData') { const [detail, members, access, schema, views, share] = await Promise.all([call(getServicePeriodProduct(numeric, opt)), call(listServicePeriodMembers(numeric, undefined, opt)), call(getServicePeriodMemberGridAccess(numeric, opt)), call(getServicePeriodMemberGridSchema(numeric, opt)), call(listServicePeriodMemberViews(numeric, opt)), call(getServicePeriodMemberGridShareSettings(numeric, opt))]); db.rows.spProducts = [serviceProductPageDto(detail)]; db.rows.orderKv = [...list(members, 'items').map((x) => ({ k: text(obj(x).name), v: text(obj(x).status), mono: false })), { k: 'member-grid', v: text(obj(schema).version), mono: false }, { k: 'views', v: String(list(views, 'items').length), mono: false }, { k: 'share', v: text(obj(share).enabled), mono: false }, { k: 'access', v: text(obj(access).role), mono: false }]; }
  if (context.page === 'couponForm' || context.page === 'couponData') { const [detail, share, claims, options] = await Promise.all([call(getLegacyCoupon(numeric, opt)), call(getLegacyCouponShare(numeric, opt)), call(listLegacyCouponClaims(numeric, undefined, opt)), call(listLegacyCouponProductOptions(undefined, opt))]); db.rows.coupons = [couponPageDto(obj(detail).coupon || detail)]; db.couponClaims[0] = list(claims, 'items', 'claims').map((x) => ({ user: text(obj(x).customer_name), status: text(obj(x).status), tone: toneFor(obj(x).status), claimedAt: text(obj(x).claimed_at), validWindow: text(obj(x).valid_window), product: text(obj(x).product_name), orderNo: text(obj(x).order_no), usedAt: text(obj(x).used_at) })); db.rows.orderKv = [...list(options, 'items').map((x) => ({ k: text(obj(x).label, text(obj(x).name)), v: text(obj(x).value, text(obj(x).id)), mono: false })), { k: 'share', v: text(obj(share).url), mono: true }]; }
  if (context.page === 'images') { const [detail, facets] = await Promise.all([call(getLegacyImage(id, undefined, opt)), call(getLegacyImageFacets(opt))]); db.rows.images = [imagePageDto(obj(detail).item || detail)]; db.rows.orderKv = [{ k: 'facets', v: String(list(facets, 'items', 'facets').length), mono: false }]; }
  if (context.page === 'attach') { const detail = await call(getLegacyAttachment(id, opt)); db.rows.attachItems = [attachmentPageDto(obj(detail).item || detail)]; }
  if (context.page === 'mpLib') { const detail = await call(getLegacyMiniProgram(numeric, opt)); db.rows.mpItems = [miniProgramPageDto(obj(detail).item || detail)]; }
  if (context.page === 'tags') { const [group, tag, gate] = await Promise.all([call(getLegacyWecomTagGroup(numeric, opt)), call(getLegacyWecomTag(numeric, opt)), call(getLegacyWecomTagExecutionGate(opt))]); db.tagGroups = [tagGroupPageDto(obj(group).group || group)]; db.wecomTags = [tagPageDto(obj(tag).tag || tag)]; db.rows.orderKv = [{ k: 'live-gate', v: text(obj(gate).status), mono: false }]; }
  return db;
}
