-- +goose Up
-- Separate from questionnaire_submissions: that table can contain identity/contact PII.
CREATE TABLE public.questionnaire_public_definitions (
 id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, questionnaire_id BIGINT NOT NULL REFERENCES public.questionnaires(id), definition_version BIGINT NOT NULL, slug TEXT NOT NULL, state TEXT NOT NULL, answer_display_mode TEXT NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL, published_at TIMESTAMPTZ, disabled_at TIMESTAMPTZ,
 CONSTRAINT questionnaire_public_definitions_version CHECK (definition_version > 0),
 CONSTRAINT questionnaire_public_definitions_state CHECK (state IN ('draft','public','disabled')), CONSTRAINT questionnaire_public_definitions_slug CHECK (slug ~ '^[a-z0-9][a-z0-9-]{0,119}$'),
 CONSTRAINT questionnaire_public_definitions_mode CHECK (answer_display_mode IN ('all_in_one','one_by_one')),
 CONSTRAINT questionnaire_public_definitions_title CHECK (btrim(title)=title AND title<>'' AND char_length(title)<=300),
 CONSTRAINT questionnaire_public_definitions_description CHECK (btrim(description)=description AND char_length(description)<=10000),
 CONSTRAINT questionnaire_public_definitions_lifecycle CHECK ((state='draft' AND published_at IS NULL AND disabled_at IS NULL) OR (state='public' AND published_at IS NOT NULL AND disabled_at IS NULL) OR (state='disabled' AND published_at IS NOT NULL AND disabled_at IS NOT NULL)),
 UNIQUE(questionnaire_id,definition_version));
CREATE UNIQUE INDEX questionnaire_public_definitions_current_public ON public.questionnaire_public_definitions(questionnaire_id) WHERE state='public';
CREATE UNIQUE INDEX questionnaire_public_definitions_current_public_slug ON public.questionnaire_public_definitions(slug) WHERE state='public';
CREATE TABLE public.questionnaire_public_definition_questions (
 id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, definition_id BIGINT NOT NULL REFERENCES public.questionnaire_public_definitions(id) ON DELETE CASCADE, source_question_id BIGINT NOT NULL, type TEXT NOT NULL, title TEXT NOT NULL, required BOOLEAN NOT NULL, sort_order INTEGER NOT NULL, minimum_selections INTEGER NOT NULL, maximum_selections INTEGER NOT NULL,
 CONSTRAINT questionnaire_public_definition_questions_type CHECK(type IN ('single_choice','multi_choice')),
 CONSTRAINT questionnaire_public_definition_questions_title CHECK(btrim(title)=title AND title<>'' AND char_length(title)<=500),
 CONSTRAINT questionnaire_public_definition_questions_order CHECK(sort_order>=0), CONSTRAINT questionnaire_public_definition_questions_range CHECK(minimum_selections>=0 AND maximum_selections>=1 AND minimum_selections<=maximum_selections), UNIQUE(definition_id,source_question_id),UNIQUE(definition_id,sort_order));
CREATE TABLE public.questionnaire_public_definition_options (
 id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, question_id BIGINT NOT NULL REFERENCES public.questionnaire_public_definition_questions(id) ON DELETE CASCADE, source_option_id BIGINT NOT NULL, option_text TEXT NOT NULL, sort_order INTEGER NOT NULL,
 CONSTRAINT questionnaire_public_definition_options_text CHECK(btrim(option_text)=option_text AND option_text<>'' AND char_length(option_text)<=500), CONSTRAINT questionnaire_public_definition_options_order CHECK(sort_order>=0), UNIQUE(question_id,source_option_id),UNIQUE(question_id,sort_order), UNIQUE(id,question_id));
CREATE TABLE public.questionnaire_public_submission_receipts (
 id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, definition_id BIGINT NOT NULL REFERENCES public.questionnaire_public_definitions(id), anonymous_digest BYTEA NOT NULL, submission_key_digest BYTEA NOT NULL, payload_digest BYTEA NOT NULL, result_token_digest BYTEA, state TEXT NOT NULL DEFAULT 'in_progress', result_snapshot JSONB, created_at TIMESTAMPTZ NOT NULL, completed_at TIMESTAMPTZ,
 CONSTRAINT questionnaire_public_submission_receipts_digest CHECK(octet_length(anonymous_digest)=32 AND octet_length(submission_key_digest)=32 AND octet_length(payload_digest)=32 AND (result_token_digest IS NULL OR octet_length(result_token_digest)=32)),
 CONSTRAINT questionnaire_public_submission_receipts_state CHECK(state IN ('in_progress','completed')),
 CONSTRAINT questionnaire_public_submission_receipts_completion CHECK((state='in_progress' AND result_snapshot IS NULL AND result_token_digest IS NULL AND completed_at IS NULL) OR (state='completed' AND result_snapshot IS NOT NULL AND result_token_digest IS NOT NULL AND completed_at IS NOT NULL)),
 UNIQUE(definition_id,anonymous_digest,submission_key_digest), UNIQUE(result_token_digest));
CREATE TABLE public.questionnaire_public_submissions (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, receipt_id BIGINT NOT NULL UNIQUE REFERENCES public.questionnaire_public_submission_receipts(id) ON DELETE CASCADE, definition_id BIGINT NOT NULL REFERENCES public.questionnaire_public_definitions(id), submitted_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL, CONSTRAINT questionnaire_public_submissions_timestamps CHECK(created_at=submitted_at));
CREATE TABLE public.questionnaire_public_submission_answers (submission_id BIGINT NOT NULL REFERENCES public.questionnaire_public_submissions(id) ON DELETE CASCADE, definition_question_id BIGINT NOT NULL REFERENCES public.questionnaire_public_definition_questions(id), definition_option_id BIGINT NOT NULL, PRIMARY KEY(submission_id,definition_question_id,definition_option_id), FOREIGN KEY(definition_option_id,definition_question_id) REFERENCES public.questionnaire_public_definition_options(id,question_id));
CREATE INDEX questionnaire_public_submission_answers_analytics ON public.questionnaire_public_submission_answers(definition_question_id,definition_option_id,submission_id);
CREATE TABLE public.questionnaire_public_submission_rate_windows (definition_id BIGINT NOT NULL REFERENCES public.questionnaire_public_definitions(id), anonymous_digest BYTEA NOT NULL, window_started_at TIMESTAMPTZ NOT NULL, attempt_count INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(definition_id,anonymous_digest,window_started_at), CONSTRAINT questionnaire_public_submission_rate_windows_digest CHECK(octet_length(anonymous_digest)=32), CONSTRAINT questionnaire_public_submission_rate_windows_count CHECK(attempt_count BETWEEN 0 AND 5));
CREATE TABLE public.questionnaire_public_management_receipts (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, operation TEXT NOT NULL, actor_scope TEXT NOT NULL, key_digest BYTEA NOT NULL, payload_digest BYTEA NOT NULL, state TEXT NOT NULL DEFAULT 'in_progress', result_snapshot JSONB, created_at TIMESTAMPTZ NOT NULL, completed_at TIMESTAMPTZ, CONSTRAINT questionnaire_public_management_receipts_operation CHECK(operation IN ('publish','disable')), CONSTRAINT questionnaire_public_management_receipts_actor CHECK(btrim(actor_scope)=actor_scope AND actor_scope<>''), CONSTRAINT questionnaire_public_management_receipts_digest CHECK(octet_length(key_digest)=32 AND octet_length(payload_digest)=32), CONSTRAINT questionnaire_public_management_receipts_state CHECK(state IN ('in_progress','completed')), CONSTRAINT questionnaire_public_management_receipts_completion CHECK((state='in_progress' AND result_snapshot IS NULL AND completed_at IS NULL) OR (state='completed' AND result_snapshot IS NOT NULL AND completed_at IS NOT NULL)), UNIQUE(operation,actor_scope,key_digest));
-- +goose StatementBegin
CREATE FUNCTION public.aicrm_questionnaire_public_receipt_complete() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$ BEGIN IF NOT EXISTS(SELECT 1 FROM public.questionnaire_public_submission_receipts WHERE id=NEW.id AND state='completed') THEN RAISE EXCEPTION 'public receipt must complete in reservation transaction' USING ERRCODE='23514'; END IF; RETURN NULL; END; $$;
-- +goose StatementEnd
CREATE CONSTRAINT TRIGGER questionnaire_public_receipt_complete_before_commit AFTER INSERT OR UPDATE ON public.questionnaire_public_submission_receipts DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.aicrm_questionnaire_public_receipt_complete();
-- +goose StatementBegin
CREATE FUNCTION public.aicrm_questionnaire_public_management_receipt_complete() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$ BEGIN IF NOT EXISTS(SELECT 1 FROM public.questionnaire_public_management_receipts WHERE id=NEW.id AND state='completed') THEN RAISE EXCEPTION 'public management receipt must complete in reservation transaction' USING ERRCODE='23514'; END IF; RETURN NULL; END; $$;
-- +goose StatementEnd
CREATE CONSTRAINT TRIGGER questionnaire_public_management_receipt_complete_before_commit AFTER INSERT OR UPDATE ON public.questionnaire_public_management_receipts DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.aicrm_questionnaire_public_management_receipt_complete();
-- +goose StatementBegin
CREATE FUNCTION public.aicrm_questionnaire_public_receipt_immutable() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$ BEGIN IF TG_OP='DELETE' OR OLD.state='completed' OR NEW.state<>'completed' OR NEW.definition_id IS DISTINCT FROM OLD.definition_id OR NEW.anonymous_digest IS DISTINCT FROM OLD.anonymous_digest OR NEW.submission_key_digest IS DISTINCT FROM OLD.submission_key_digest OR NEW.payload_digest IS DISTINCT FROM OLD.payload_digest OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN RAISE EXCEPTION 'invalid public receipt transition' USING ERRCODE='55000'; END IF; RETURN NEW; END; $$;
-- +goose StatementEnd
CREATE TRIGGER questionnaire_public_receipt_transition BEFORE UPDATE OR DELETE ON public.questionnaire_public_submission_receipts FOR EACH ROW EXECUTE FUNCTION public.aicrm_questionnaire_public_receipt_immutable();
-- +goose StatementBegin
CREATE FUNCTION public.aicrm_questionnaire_public_management_receipt_immutable() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$ BEGIN IF TG_OP='DELETE' OR OLD.state='completed' OR NEW.state<>'completed' OR NEW.operation IS DISTINCT FROM OLD.operation OR NEW.actor_scope IS DISTINCT FROM OLD.actor_scope OR NEW.key_digest IS DISTINCT FROM OLD.key_digest OR NEW.payload_digest IS DISTINCT FROM OLD.payload_digest OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN RAISE EXCEPTION 'invalid public management receipt transition' USING ERRCODE='55000'; END IF; RETURN NEW; END; $$;
-- +goose StatementEnd
CREATE TRIGGER questionnaire_public_management_receipt_transition BEFORE UPDATE OR DELETE ON public.questionnaire_public_management_receipts FOR EACH ROW EXECUTE FUNCTION public.aicrm_questionnaire_public_management_receipt_immutable();
CREATE TRIGGER questionnaire_public_submissions_immutable BEFORE UPDATE ON public.questionnaire_public_submissions FOR EACH ROW EXECUTE FUNCTION public.aicrm_questionnaire_submission_immutable();
CREATE TRIGGER questionnaire_public_submission_answers_immutable BEFORE UPDATE ON public.questionnaire_public_submission_answers FOR EACH ROW EXECUTE FUNCTION public.aicrm_questionnaire_submission_immutable();
-- +goose StatementBegin
CREATE FUNCTION public.aicrm_questionnaire_public_definition_immutable() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$ BEGIN IF TG_OP='DELETE' OR OLD.state<>'public' OR NEW.state<>'disabled' OR NEW.questionnaire_id IS DISTINCT FROM OLD.questionnaire_id OR NEW.definition_version IS DISTINCT FROM OLD.definition_version OR NEW.slug IS DISTINCT FROM OLD.slug OR NEW.answer_display_mode IS DISTINCT FROM OLD.answer_display_mode OR NEW.title IS DISTINCT FROM OLD.title OR NEW.description IS DISTINCT FROM OLD.description OR NEW.created_at IS DISTINCT FROM OLD.created_at OR NEW.published_at IS DISTINCT FROM OLD.published_at OR NEW.disabled_at IS NULL THEN RAISE EXCEPTION 'public definition is immutable except public to disabled' USING ERRCODE='55000'; END IF; RETURN NEW; END; $$;
-- +goose StatementEnd
CREATE TRIGGER questionnaire_public_definitions_immutable BEFORE UPDATE OR DELETE ON public.questionnaire_public_definitions FOR EACH ROW EXECUTE FUNCTION public.aicrm_questionnaire_public_definition_immutable();
CREATE TRIGGER questionnaire_public_definition_questions_immutable BEFORE UPDATE OR DELETE ON public.questionnaire_public_definition_questions FOR EACH ROW EXECUTE FUNCTION public.aicrm_questionnaire_submission_immutable();
CREATE TRIGGER questionnaire_public_definition_options_immutable BEFORE UPDATE OR DELETE ON public.questionnaire_public_definition_options FOR EACH ROW EXECUTE FUNCTION public.aicrm_questionnaire_submission_immutable();
-- +goose Down
DROP TRIGGER questionnaire_public_definition_options_immutable ON public.questionnaire_public_definition_options; DROP TRIGGER questionnaire_public_definition_questions_immutable ON public.questionnaire_public_definition_questions; DROP TRIGGER questionnaire_public_definitions_immutable ON public.questionnaire_public_definitions; DROP TRIGGER questionnaire_public_submission_answers_immutable ON public.questionnaire_public_submission_answers; DROP TRIGGER questionnaire_public_submissions_immutable ON public.questionnaire_public_submissions; DROP TRIGGER questionnaire_public_management_receipt_transition ON public.questionnaire_public_management_receipts; DROP TRIGGER questionnaire_public_receipt_transition ON public.questionnaire_public_submission_receipts; DROP TRIGGER questionnaire_public_management_receipt_complete_before_commit ON public.questionnaire_public_management_receipts; DROP TRIGGER questionnaire_public_receipt_complete_before_commit ON public.questionnaire_public_submission_receipts; DROP FUNCTION public.aicrm_questionnaire_public_definition_immutable(); DROP FUNCTION public.aicrm_questionnaire_public_receipt_immutable(); DROP FUNCTION public.aicrm_questionnaire_public_management_receipt_immutable(); DROP FUNCTION public.aicrm_questionnaire_public_management_receipt_complete(); DROP FUNCTION public.aicrm_questionnaire_public_receipt_complete(); DROP INDEX IF EXISTS questionnaire_public_definitions_current_public_slug; DROP TABLE public.questionnaire_public_management_receipts; DROP TABLE public.questionnaire_public_submission_rate_windows; DROP TABLE public.questionnaire_public_submission_answers; DROP TABLE public.questionnaire_public_submissions; DROP TABLE public.questionnaire_public_submission_receipts; DROP TABLE public.questionnaire_public_definition_options; DROP TABLE public.questionnaire_public_definition_questions; DROP TABLE public.questionnaire_public_definitions;
