-- +goose Up
CREATE TABLE public.radar_links (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_code     TEXT NOT NULL,
    name            TEXT NOT NULL,
    title           TEXT NOT NULL,
    destination_url TEXT NOT NULL,
    cover_image_id  BIGINT NULL,
    attachment_id   BIGINT NULL,
    status          TEXT NOT NULL DEFAULT 'draft',
    version         BIGINT NOT NULL DEFAULT 1,
    created_by      BIGINT NOT NULL,
    updated_by      BIGINT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL,

    CONSTRAINT radar_links_public_code_unique UNIQUE (public_code),
    CONSTRAINT radar_links_public_code_format_check
        CHECK (public_code ~ '^rd_[A-Za-z0-9_-]{22}$'),
    CONSTRAINT radar_links_name_check
        CHECK (char_length(name) BETWEEN 1 AND 120 AND btrim(name) = name),
    CONSTRAINT radar_links_title_check
        CHECK (char_length(title) BETWEEN 1 AND 200 AND btrim(title) = title),
    CONSTRAINT radar_links_destination_url_check
        CHECK (
            octet_length(destination_url) BETWEEN 1 AND 2048
            AND destination_url LIKE 'https://%'
            AND btrim(destination_url) = destination_url
        ),
    CONSTRAINT radar_links_cover_image_id_check
        CHECK (cover_image_id IS NULL OR cover_image_id > 0),
    CONSTRAINT radar_links_attachment_id_check
        CHECK (attachment_id IS NULL OR attachment_id > 0),
    CONSTRAINT radar_links_status_check
        CHECK (status IN ('draft', 'enabled', 'disabled')),
    CONSTRAINT radar_links_version_check CHECK (version >= 1),
    CONSTRAINT radar_links_created_by_check CHECK (created_by > 0),
    CONSTRAINT radar_links_updated_by_check CHECK (updated_by > 0),
    CONSTRAINT radar_links_timestamp_order_check CHECK (updated_at >= created_at)
);

COMMENT ON TABLE public.radar_links IS
    'Local-only Radar link management facts. No public route, click tracking, upload, or provider effect is implied.';
COMMENT ON COLUMN public.radar_links.public_code IS
    'Immutable local share descriptor code; uniqueness does not imply public reachability.';
COMMENT ON COLUMN public.radar_links.destination_url IS
    'Application-validated absolute HTTPS URL. Validation never resolves DNS or issues an HTTP request.';
COMMENT ON COLUMN public.radar_links.cover_image_id IS
    'Optional positive local reference; no foreign key or remote validation in Lane D1.';
COMMENT ON COLUMN public.radar_links.attachment_id IS
    'Optional positive local reference; no foreign key or remote validation in Lane D1.';

CREATE INDEX radar_links_status_updated_id_idx
    ON public.radar_links (status, updated_at DESC, id DESC);
CREATE INDEX radar_links_updated_id_idx
    ON public.radar_links (updated_at DESC, id DESC);
CREATE INDEX radar_links_created_id_idx
    ON public.radar_links (created_at DESC, id DESC);
CREATE INDEX radar_links_name_id_idx
    ON public.radar_links (name ASC, id ASC);

-- +goose StatementBegin
CREATE FUNCTION public.radar_links_reject_public_code_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.public_code IS DISTINCT FROM OLD.public_code THEN
        RAISE EXCEPTION 'radar_links.public_code is immutable'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER radar_links_public_code_immutable
BEFORE UPDATE OF public_code ON public.radar_links
FOR EACH ROW
EXECUTE FUNCTION public.radar_links_reject_public_code_change();

CREATE TABLE public.radar_link_idempotency_records (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id               BIGINT NOT NULL,
    key_digest             BYTEA NOT NULL,
    operation              TEXT NOT NULL,
    payload_digest         BYTEA NOT NULL,
    state                  TEXT NOT NULL,

    -- Closed typed result snapshot. There is intentionally no generic JSON,
    -- opaque payload, provider result, or external-effect acknowledgment.
    result_link_id          BIGINT NULL,
    result_public_code      TEXT NULL,
    result_name             TEXT NULL,
    result_title            TEXT NULL,
    result_destination_url  TEXT NULL,
    result_cover_image_id   BIGINT NULL,
    result_attachment_id    BIGINT NULL,
    result_status           TEXT NULL,
    result_version          BIGINT NULL,
    result_created_by       BIGINT NULL,
    result_updated_by       BIGINT NULL,
    result_created_at       TIMESTAMPTZ NULL,
    result_updated_at       TIMESTAMPTZ NULL,

    created_at              TIMESTAMPTZ NOT NULL,
    completed_at            TIMESTAMPTZ NULL,

    CONSTRAINT radar_link_idempotency_actor_key_unique
        UNIQUE (actor_id, key_digest),
    CONSTRAINT radar_link_idempotency_actor_check CHECK (actor_id > 0),
    CONSTRAINT radar_link_idempotency_key_digest_check
        CHECK (octet_length(key_digest) = 32),
    CONSTRAINT radar_link_idempotency_payload_digest_check
        CHECK (octet_length(payload_digest) = 32),
    CONSTRAINT radar_link_idempotency_operation_check
        CHECK (operation IN ('create', 'update', 'enable', 'disable')),
    CONSTRAINT radar_link_idempotency_state_check
        CHECK (state IN ('reserved', 'completed')),
    CONSTRAINT radar_link_idempotency_result_public_code_check
        CHECK (result_public_code IS NULL OR result_public_code ~ '^rd_[A-Za-z0-9_-]{22}$'),
    CONSTRAINT radar_link_idempotency_result_name_check
        CHECK (
            result_name IS NULL
            OR (char_length(result_name) BETWEEN 1 AND 120 AND btrim(result_name) = result_name)
        ),
    CONSTRAINT radar_link_idempotency_result_title_check
        CHECK (
            result_title IS NULL
            OR (char_length(result_title) BETWEEN 1 AND 200 AND btrim(result_title) = result_title)
        ),
    CONSTRAINT radar_link_idempotency_result_url_check
        CHECK (
            result_destination_url IS NULL
            OR (
                octet_length(result_destination_url) BETWEEN 1 AND 2048
                AND result_destination_url LIKE 'https://%'
                AND btrim(result_destination_url) = result_destination_url
            )
        ),
    CONSTRAINT radar_link_idempotency_result_status_check
        CHECK (result_status IS NULL OR result_status IN ('draft', 'enabled', 'disabled')),
    CONSTRAINT radar_link_idempotency_result_ids_check
        CHECK (
            (result_link_id IS NULL OR result_link_id > 0)
            AND (result_cover_image_id IS NULL OR result_cover_image_id > 0)
            AND (result_attachment_id IS NULL OR result_attachment_id > 0)
            AND (result_version IS NULL OR result_version >= 1)
            AND (result_created_by IS NULL OR result_created_by > 0)
            AND (result_updated_by IS NULL OR result_updated_by > 0)
        ),
    CONSTRAINT radar_link_idempotency_result_timestamp_check
        CHECK (
            result_updated_at IS NULL
            OR (result_created_at IS NOT NULL AND result_updated_at >= result_created_at)
        ),
    CONSTRAINT radar_link_idempotency_completion_check
        CHECK (
            (
                state = 'reserved'
                AND result_link_id IS NULL
                AND result_public_code IS NULL
                AND result_name IS NULL
                AND result_title IS NULL
                AND result_destination_url IS NULL
                AND result_cover_image_id IS NULL
                AND result_attachment_id IS NULL
                AND result_status IS NULL
                AND result_version IS NULL
                AND result_created_by IS NULL
                AND result_updated_by IS NULL
                AND result_created_at IS NULL
                AND result_updated_at IS NULL
                AND completed_at IS NULL
            )
            OR
            (
                state = 'completed'
                AND result_link_id IS NOT NULL
                AND result_public_code IS NOT NULL
                AND result_name IS NOT NULL
                AND result_title IS NOT NULL
                AND result_destination_url IS NOT NULL
                AND result_status IS NOT NULL
                AND result_version IS NOT NULL
                AND result_created_by IS NOT NULL
                AND result_updated_by IS NOT NULL
                AND result_created_at IS NOT NULL
                AND result_updated_at IS NOT NULL
                AND completed_at IS NOT NULL
            )
        ),
    CONSTRAINT radar_link_idempotency_timestamp_order_check
        CHECK (completed_at IS NULL OR completed_at >= created_at)
);

COMMENT ON TABLE public.radar_link_idempotency_records IS
    'Transactional local mutation deduplication with typed result columns. Stores SHA-256 key digests, never raw Idempotency-Key values, generic JSON, or provider data.';


-- +goose Down
DROP TRIGGER IF EXISTS radar_links_public_code_immutable ON public.radar_links;
DROP FUNCTION IF EXISTS public.radar_links_reject_public_code_change();
DROP TABLE IF EXISTS public.radar_link_idempotency_records;
DROP TABLE IF EXISTS public.radar_links;
