-- +goose Up
-- Radar tracking facts intentionally exclude IP addresses, user agents,
-- referrers, query strings and customer identity. OAuth/Provider attribution is
-- a separate, externally gated capability.
CREATE TABLE public.radar_link_events (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id     TEXT NOT NULL UNIQUE,
    link_id        BIGINT NOT NULL REFERENCES public.radar_links(id) ON DELETE RESTRICT,
    stage          TEXT NOT NULL,
    page_no        INTEGER NULL,
    source         TEXT NOT NULL,
    key_digest     BYTEA NULL,
    payload_digest BYTEA NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL,

    CONSTRAINT radar_link_events_receipt_id_check
        CHECK (receipt_id ~ '^rre_[0-9a-f]{32}$'),
    CONSTRAINT radar_link_events_stage_check CHECK (stage IN (
        'landing', 'redirect', 'viewer_open', 'image_loaded', 'pdf_opened',
        'pdf_manifest_loaded', 'pdf_page_loaded', 'pdf_page_error',
        'image_manifest_loaded', 'image_variant_loaded'
    )),
    CONSTRAINT radar_link_events_page_check
        CHECK (page_no IS NULL OR page_no BETWEEN 1 AND 100000),
    CONSTRAINT radar_link_events_source_check
        CHECK (source IN ('public_redirect', 'public_event')),
    CONSTRAINT radar_link_events_key_digest_check
        CHECK (key_digest IS NULL OR octet_length(key_digest) = 32),
    CONSTRAINT radar_link_events_payload_digest_check
        CHECK (octet_length(payload_digest) = 32),
    CONSTRAINT radar_link_events_source_key_check CHECK (
        (source = 'public_redirect' AND key_digest IS NULL)
        OR (source = 'public_event' AND key_digest IS NOT NULL)
    ),
    CONSTRAINT radar_link_events_link_key_unique UNIQUE (link_id, key_digest)
);

CREATE INDEX radar_link_events_link_created_id_idx
    ON public.radar_link_events (link_id, created_at DESC, id DESC);
CREATE INDEX radar_link_events_link_stage_created_id_idx
    ON public.radar_link_events (link_id, stage, created_at DESC, id DESC);

COMMENT ON TABLE public.radar_link_events IS
    'Immutable local Radar tracking receipts without identity, IP, user-agent, referrer, query string, OAuth or Provider facts.';
COMMENT ON COLUMN public.radar_link_events.key_digest IS
    'SHA-256 digest of a public event Idempotency-Key; raw keys are never stored.';
COMMENT ON COLUMN public.radar_link_events.payload_digest IS
    'SHA-256 digest of the canonical accepted event payload; raw extra payload is never stored.';

-- +goose StatementBegin
CREATE FUNCTION public.radar_link_events_reject_change()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $$
BEGIN
    RAISE EXCEPTION 'radar link event receipts are immutable' USING ERRCODE = '55000';
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER radar_link_events_change_guard
BEFORE UPDATE OR DELETE ON public.radar_link_events
FOR EACH ROW EXECUTE FUNCTION public.radar_link_events_reject_change();

-- +goose Down
LOCK TABLE public.radar_link_events IN SHARE ROW EXCLUSIVE MODE;
-- +goose StatementBegin
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM public.radar_link_events) THEN
        RAISE EXCEPTION 'cannot roll back populated radar local tracking' USING ERRCODE = '55000';
    END IF;
END;
$$;
-- +goose StatementEnd
DROP TRIGGER radar_link_events_change_guard ON public.radar_link_events;
DROP FUNCTION public.radar_link_events_reject_change();
DROP TABLE public.radar_link_events;
