-- +goose Up

CREATE TABLE outbound_v1_broadcast_job_history (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  source_id BIGINT NOT NULL,
  original_source_type TEXT NOT NULL,
  source_reference_digest BYTEA NOT NULL CHECK (octet_length(source_reference_digest) = 32),
  source_table TEXT NOT NULL,
  scheduled_for TIMESTAMPTZ NOT NULL,
  priority INTEGER NOT NULL,
  batch_key_digest BYTEA NOT NULL CHECK (octet_length(batch_key_digest) = 32),
  original_status TEXT NOT NULL,
  requires_approval BOOLEAN NOT NULL,
  approved_by_digest BYTEA NOT NULL CHECK (octet_length(approved_by_digest) = 32),
  approved_at TIMESTAMPTZ,
  cancelled_by_digest BYTEA NOT NULL CHECK (octet_length(cancelled_by_digest) = 32),
  cancelled_at TIMESTAMPTZ,
  cancel_reason_digest BYTEA NOT NULL CHECK (octet_length(cancel_reason_digest) = 32),
  target_count INTEGER NOT NULL,
  target_summary_digest BYTEA NOT NULL CHECK (octet_length(target_summary_digest) = 32),
  content_type TEXT NOT NULL,
  content_payload_digest BYTEA NOT NULL CHECK (octet_length(content_payload_digest) = 32),
  content_summary_digest BYTEA NOT NULL CHECK (octet_length(content_summary_digest) = 32),
  attempt_count INTEGER NOT NULL,
  last_error_digest BYTEA NOT NULL CHECK (octet_length(last_error_digest) = 32),
  legacy_outbound_task_id BIGINT,
  sent_count INTEGER NOT NULL,
  failed_count INTEGER NOT NULL,
  trace_id_digest BYTEA NOT NULL CHECK (octet_length(trace_id_digest) = 32),
  created_by_digest BYTEA NOT NULL CHECK (octet_length(created_by_digest) = 32),
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  claimed_at TIMESTAMPTZ,
  sent_at TIMESTAMPTZ,
  claim_token_digest BYTEA NOT NULL CHECK (octet_length(claim_token_digest) = 32),
  lease_expires_at TIMESTAMPTZ,
  business_domain TEXT,
  idempotency_key_digest BYTEA CHECK (idempotency_key_digest IS NULL OR octet_length(idempotency_key_digest) = 32),
  channel TEXT,
  target_kind TEXT,
  failure_type TEXT,
  retry_policy_digest BYTEA NOT NULL CHECK (octet_length(retry_policy_digest) = 32),
  metadata_digest BYTEA NOT NULL CHECK (octet_length(metadata_digest) = 32),
  target_union_i_ds_digest BYTEA NOT NULL CHECK (octet_length(target_union_i_ds_digest) = 32),
  max_attempts INTEGER NOT NULL,
  next_retry_at TIMESTAMPTZ,
  dispatch_started_at TIMESTAMPTZ,
  original_side_effect_executed BOOLEAN NOT NULL,
  original_provider_result_received BOOLEAN NOT NULL,
  result_summary_digest BYTEA NOT NULL CHECK (octet_length(result_summary_digest) = 32),
  original_reconciliation_required BOOLEAN NOT NULL,
  completed_at TIMESTAMPTZ,
  hold_reason_digest BYTEA NOT NULL CHECK (octet_length(hold_reason_digest) = 32),
  hold_at TIMESTAMPTZ,
  legacy_external_effect_job_id BIGINT,
  execution_id_digest BYTEA NOT NULL CHECK (octet_length(execution_id_digest) = 32),
  execution_owner_digest BYTEA NOT NULL CHECK (octet_length(execution_owner_digest) = 32),
  source_key_digest BYTEA NOT NULL UNIQUE CHECK (octet_length(source_key_digest) = 32),
  source_payload_digest BYTEA NOT NULL CHECK (octet_length(source_payload_digest) = 32),
  source_field_digest BYTEA NOT NULL CHECK (octet_length(source_field_digest) = 32),
  redacted_roots TEXT[] NOT NULL
);

-- +goose Down
DROP TABLE outbound_v1_broadcast_job_history;
