-- name: CreateHistoricalHXCChatJob :one
INSERT INTO hxc_v1_chat_job_history (source_id, source_key_digest, source_payload_digest, source_field_digest, queue_source_id, member_source_id, external_contact_id, phone, external_message_id, external_session_id, laohuang_task_id, request_payload_json, accepted_payload_json, callback_payload_json, original_status, reply_text, error_code, error_message, send_channel, send_record_source_id, send_result_json, created_at, updated_at, finished_at_source) VALUES (sqlc.arg(source_id), sqlc.arg(source_key_digest), sqlc.arg(source_payload_digest), sqlc.arg(source_field_digest), sqlc.narg(queue_source_id), sqlc.narg(member_source_id), sqlc.arg(external_contact_id), sqlc.arg(phone), sqlc.arg(external_message_id), sqlc.arg(external_session_id), sqlc.arg(laohuang_task_id), sqlc.arg(request_payload_json), sqlc.arg(accepted_payload_json), sqlc.arg(callback_payload_json), sqlc.arg(original_status), sqlc.arg(reply_text), sqlc.arg(error_code), sqlc.arg(error_message), sqlc.arg(send_channel), sqlc.narg(send_record_source_id), sqlc.arg(send_result_json), sqlc.arg(created_at), sqlc.arg(updated_at), sqlc.arg(finished_at_source)) RETURNING id, source_id, source_key_digest, source_payload_digest, source_field_digest, queue_source_id, member_source_id, external_contact_id, phone, external_message_id, external_session_id, laohuang_task_id, request_payload_json, accepted_payload_json, callback_payload_json, original_status, reply_text, error_code, error_message, send_channel, send_record_source_id, send_result_json, created_at, updated_at, finished_at_source;

-- name: GetHistoricalHXCChatJob :one
SELECT id, source_id, source_key_digest, source_payload_digest, source_field_digest, queue_source_id, member_source_id, external_contact_id, phone, external_message_id, external_session_id, laohuang_task_id, request_payload_json, accepted_payload_json, callback_payload_json, original_status, reply_text, error_code, error_message, send_channel, send_record_source_id, send_result_json, created_at, updated_at, finished_at_source FROM hxc_v1_chat_job_history WHERE id = sqlc.arg(id);

-- name: ListHistoricalHXCChatJob :many
SELECT id, source_id, source_key_digest, source_payload_digest, source_field_digest, queue_source_id, member_source_id, external_contact_id, phone, external_message_id, external_session_id, laohuang_task_id, request_payload_json, accepted_payload_json, callback_payload_json, original_status, reply_text, error_code, error_message, send_channel, send_record_source_id, send_result_json, created_at, updated_at, finished_at_source FROM hxc_v1_chat_job_history ORDER BY id ASC LIMIT sqlc.arg(row_limit) OFFSET sqlc.arg(row_offset);

-- name: CountHistoricalHXCChatJob :one
SELECT count(*)::bigint FROM hxc_v1_chat_job_history;
