-- name: CreateHistoricalHXCMemberUsage :one
INSERT INTO hxc_v1_member_usage_history (source_key_digest, source_payload_digest, source_field_digest, generation, unionid, owner_userid, mobile_hash, is_member, is_registered, registered_at, has_real_usage, first_used_at, last_used_at, member_since, membership_expires_at, membership_tier, membership_status, membership_source, registration_source, usage_source, updated_at, payload_json, projected_at) VALUES (sqlc.arg(source_key_digest), sqlc.arg(source_payload_digest), sqlc.arg(source_field_digest), sqlc.arg(generation), sqlc.arg(unionid), sqlc.arg(owner_userid), sqlc.arg(mobile_hash), sqlc.arg(is_member), sqlc.arg(is_registered), sqlc.narg(registered_at), sqlc.arg(has_real_usage), sqlc.narg(first_used_at), sqlc.narg(last_used_at), sqlc.narg(member_since), sqlc.narg(membership_expires_at), sqlc.arg(membership_tier), sqlc.arg(membership_status), sqlc.arg(membership_source), sqlc.arg(registration_source), sqlc.arg(usage_source), sqlc.narg(updated_at), sqlc.arg(payload_json), sqlc.arg(projected_at)) RETURNING id, source_key_digest, source_payload_digest, source_field_digest, generation, unionid, owner_userid, mobile_hash, is_member, is_registered, registered_at, has_real_usage, first_used_at, last_used_at, member_since, membership_expires_at, membership_tier, membership_status, membership_source, registration_source, usage_source, updated_at, payload_json, projected_at;

-- name: GetHistoricalHXCMemberUsage :one
SELECT id, source_key_digest, source_payload_digest, source_field_digest, generation, unionid, owner_userid, mobile_hash, is_member, is_registered, registered_at, has_real_usage, first_used_at, last_used_at, member_since, membership_expires_at, membership_tier, membership_status, membership_source, registration_source, usage_source, updated_at, payload_json, projected_at FROM hxc_v1_member_usage_history WHERE id = sqlc.arg(id);

-- name: ListHistoricalHXCMemberUsage :many
SELECT id, source_key_digest, source_payload_digest, source_field_digest, generation, unionid, owner_userid, mobile_hash, is_member, is_registered, registered_at, has_real_usage, first_used_at, last_used_at, member_since, membership_expires_at, membership_tier, membership_status, membership_source, registration_source, usage_source, updated_at, payload_json, projected_at FROM hxc_v1_member_usage_history WHERE (sqlc.narg(generation)::bigint IS NULL OR generation = sqlc.narg(generation)::bigint) ORDER BY id ASC LIMIT sqlc.arg(row_limit) OFFSET sqlc.arg(row_offset);

-- name: CountHistoricalHXCMemberUsage :one
SELECT count(*)::bigint FROM hxc_v1_member_usage_history WHERE (sqlc.narg(generation)::bigint IS NULL OR generation = sqlc.narg(generation)::bigint);
