// Package deployment owns deterministic, non-secret deployment configuration.
package deployment

import (
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

const (
	EnvironmentFileName = "aicrm.env"
	PostgreSQLFileName  = "postgresql.conf"
)

var (
	ErrInvalidTier      = errors.New("invalid deployment tier")
	ErrUnsafeOutputPath = errors.New("unsafe deployment output path")
)

type Tier string

const (
	TierS Tier = "s"
	TierM Tier = "m"
	TierL Tier = "l"
)

type QueueConcurrency struct {
	Critical int
	Event    int
	Outbound int
	Sync     int
	Heavy    int
	AI       int
}

func (queues QueueConcurrency) Total() int {
	return queues.Critical + queues.Event + queues.Outbound + queues.Sync + queues.Heavy + queues.AI
}

type Config struct {
	Tier                  Tier
	ComposeProfile        string
	SharedBuffers         string
	EffectiveCacheSize    string
	WorkMem               string
	MaintenanceWorkMem    string
	MaxConnections        int
	GoMemoryLimit         string
	APIPoolMaxConnections int
	WorkerPoolMaxConns    int
	Queues                QueueConcurrency
	OutboundBatchChunk    int
	SwapTargetMiB         int
	SwapPolicy            string
}

var configs = map[Tier]Config{
	TierS: {
		Tier:                  TierS,
		ComposeProfile:        "combined",
		SharedBuffers:         "1GB",
		EffectiveCacheSize:    "2GB",
		WorkMem:               "8MB",
		MaintenanceWorkMem:    "128MB",
		MaxConnections:        40,
		GoMemoryLimit:         "768MiB",
		APIPoolMaxConnections: 10,
		WorkerPoolMaxConns:    9,
		Queues: QueueConcurrency{
			Critical: 2,
			Event:    1,
			Outbound: 1,
			Sync:     1,
			Heavy:    1,
			AI:       1,
		},
		OutboundBatchChunk: 1000,
		SwapTargetMiB:      4096,
		SwapPolicy:         "required",
	},
	TierM: {
		Tier:                  TierM,
		ComposeProfile:        "split",
		SharedBuffers:         "2GB",
		EffectiveCacheSize:    "5GB",
		WorkMem:               "16MB",
		MaintenanceWorkMem:    "256MB",
		MaxConnections:        80,
		GoMemoryLimit:         "1536MiB",
		APIPoolMaxConnections: 20,
		WorkerPoolMaxConns:    18,
		Queues: QueueConcurrency{
			Critical: 3,
			Event:    2,
			Outbound: 4,
			Sync:     2,
			Heavy:    2,
			AI:       2,
		},
		OutboundBatchChunk: 5000,
		SwapTargetMiB:      2048,
		SwapPolicy:         "recommended",
	},
	TierL: {
		Tier:                  TierL,
		ComposeProfile:        "split",
		SharedBuffers:         "4GB",
		EffectiveCacheSize:    "10GB",
		WorkMem:               "32MB",
		MaintenanceWorkMem:    "512MB",
		MaxConnections:        150,
		GoMemoryLimit:         "3GiB",
		APIPoolMaxConnections: 30,
		WorkerPoolMaxConns:    30,
		Queues: QueueConcurrency{
			Critical: 4,
			Event:    4,
			Outbound: 8,
			Sync:     3,
			Heavy:    4,
			AI:       3,
		},
		OutboundBatchChunk: 10000,
		SwapTargetMiB:      0,
		SwapPolicy:         "optional",
	},
}

func Lookup(value string) (Config, error) {
	config, ok := configs[Tier(value)]
	if !ok {
		return Config{}, ErrInvalidTier
	}
	if config.WorkerPoolMaxConns < config.Queues.Total()+2 {
		return Config{}, ErrInvalidTier
	}
	return config, nil
}

func (config Config) RenderPostgreSQL() string {
	return fmt.Sprintf(`# Generated by aicrm-config. Do not edit.
listen_addresses = '*'
shared_buffers = '%s'
effective_cache_size = '%s'
work_mem = '%s'
maintenance_work_mem = '%s'
max_connections = %d
`, config.SharedBuffers, config.EffectiveCacheSize, config.WorkMem,
		config.MaintenanceWorkMem, config.MaxConnections)
}

func (config Config) RenderEnvironment() string {
	return fmt.Sprintf(`# Generated by aicrm-config. Contains no credentials.
AICRM_TIER=%s
COMPOSE_PROFILES=%s
GOMEMLIMIT=%s
AICRM_HTTP_LISTEN_ADDRESS=:8080
AICRM_API_PGX_MAX_CONNS=%d
AICRM_WORKER_PGX_MAX_CONNS=%d
AICRM_RIVER_CRITICAL_MAX_WORKERS=%d
AICRM_RIVER_EVENT_MAX_WORKERS=%d
AICRM_RIVER_OUTBOUND_MAX_WORKERS=%d
AICRM_RIVER_SYNC_MAX_WORKERS=%d
AICRM_RIVER_HEAVY_MAX_WORKERS=%d
AICRM_RIVER_AI_MAX_WORKERS=%d
AICRM_OUTBOUND_BATCH_CHUNK=%d
AICRM_SWAP_TARGET_MIB=%d
AICRM_SWAP_POLICY=%s
AICRM_WORKER_HEAVY_TASK_WINDOW=01:00-06:00
AICRM_RIVER_CRITICAL_TIMEOUT=30s
`, config.Tier, config.ComposeProfile, config.GoMemoryLimit,
		config.APIPoolMaxConnections, config.WorkerPoolMaxConns,
		config.Queues.Critical, config.Queues.Event, config.Queues.Outbound,
		config.Queues.Sync, config.Queues.Heavy, config.Queues.AI,
		config.OutboundBatchChunk, config.SwapTargetMiB, config.SwapPolicy)
}

func Generate(config Config, outputDirectory string) error {
	directory, err := prepareOutputDirectory(outputDirectory)
	if err != nil {
		return err
	}
	if err := writeAtomic(directory, PostgreSQLFileName, config.RenderPostgreSQL()); err != nil {
		return err
	}
	return writeAtomic(directory, EnvironmentFileName, config.RenderEnvironment())
}

func prepareOutputDirectory(value string) (string, error) {
	if value == "" || strings.TrimSpace(value) != value {
		return "", ErrUnsafeOutputPath
	}
	absolute, err := filepath.Abs(value)
	if err != nil || absolute == string(filepath.Separator) {
		return "", ErrUnsafeOutputPath
	}
	absolute, err = canonicalOutputPath(absolute)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(absolute, 0o750); err != nil {
		return "", fmt.Errorf("create deployment output: %w", err)
	}
	if err := os.Chmod(absolute, 0o750); err != nil {
		return "", fmt.Errorf("secure deployment output: %w", err)
	}
	return absolute, nil
}

func canonicalOutputPath(absolute string) (string, error) {
	if info, err := os.Lstat(absolute); err == nil {
		if info.Mode()&os.ModeSymlink != 0 || !info.IsDir() {
			return "", ErrUnsafeOutputPath
		}
		resolved, err := filepath.EvalSymlinks(absolute)
		if err != nil {
			return "", ErrUnsafeOutputPath
		}
		return resolved, nil
	} else if !errors.Is(err, os.ErrNotExist) {
		return "", ErrUnsafeOutputPath
	}

	ancestor := absolute
	var missing []string
	for {
		missing = append([]string{filepath.Base(ancestor)}, missing...)
		ancestor = filepath.Dir(ancestor)
		info, err := os.Lstat(ancestor)
		if err == nil {
			if !info.IsDir() && info.Mode()&os.ModeSymlink == 0 {
				return "", ErrUnsafeOutputPath
			}
			resolved, err := filepath.EvalSymlinks(ancestor)
			if err != nil {
				return "", ErrUnsafeOutputPath
			}
			return filepath.Join(append([]string{resolved}, missing...)...), nil
		}
		if !errors.Is(err, os.ErrNotExist) || ancestor == filepath.Dir(ancestor) {
			return "", ErrUnsafeOutputPath
		}
	}
}

func writeAtomic(directory, name, content string) error {
	target := filepath.Join(directory, name)
	if info, err := os.Lstat(target); err == nil {
		if info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() {
			return ErrUnsafeOutputPath
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("inspect deployment output: %w", err)
	}

	temporary, err := os.CreateTemp(directory, ".aicrm-config-*")
	if err != nil {
		return fmt.Errorf("create deployment output: %w", err)
	}
	temporaryName := temporary.Name()
	defer os.Remove(temporaryName)
	if err := temporary.Chmod(0o640); err != nil {
		temporary.Close()
		return fmt.Errorf("secure deployment output: %w", err)
	}
	if _, err := io.WriteString(temporary, content); err != nil {
		temporary.Close()
		return fmt.Errorf("write deployment output: %w", err)
	}
	if err := temporary.Sync(); err != nil {
		temporary.Close()
		return fmt.Errorf("sync deployment output: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("close deployment output: %w", err)
	}
	if err := os.Rename(temporaryName, target); err != nil {
		return fmt.Errorf("publish deployment output: %w", err)
	}
	return nil
}
