package deployment

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestTierTable(t *testing.T) {
	t.Parallel()
	tests := []struct {
		tier       string
		profile    string
		postgres   string
		memory     string
		apiPool    int
		workerPool int
		queues     QueueConcurrency
		chunk      int
		swap       int
		swapPolicy string
	}{
		{"s", "combined", "# Generated by aicrm-config. Do not edit.\nshared_buffers = '1GB'\neffective_cache_size = '2GB'\nwork_mem = '8MB'\nmaintenance_work_mem = '128MB'\nmax_connections = 40\n", "768MiB", 10, 9, QueueConcurrency{2, 1, 1, 1, 1, 1}, 1000, 4096, "required"},
		{"m", "split", "# Generated by aicrm-config. Do not edit.\nshared_buffers = '2GB'\neffective_cache_size = '5GB'\nwork_mem = '16MB'\nmaintenance_work_mem = '256MB'\nmax_connections = 80\n", "1536MiB", 20, 18, QueueConcurrency{3, 2, 4, 2, 2, 2}, 5000, 2048, "recommended"},
		{"l", "split", "# Generated by aicrm-config. Do not edit.\nshared_buffers = '4GB'\neffective_cache_size = '10GB'\nwork_mem = '32MB'\nmaintenance_work_mem = '512MB'\nmax_connections = 150\n", "3GiB", 30, 30, QueueConcurrency{4, 4, 8, 3, 4, 3}, 10000, 0, "optional"},
	}
	for _, test := range tests {
		t.Run(test.tier, func(t *testing.T) {
			config, err := Lookup(test.tier)
			if err != nil {
				t.Fatal(err)
			}
			if config.ComposeProfile != test.profile || config.GoMemoryLimit != test.memory ||
				config.APIPoolMaxConnections != test.apiPool || config.WorkerPoolMaxConns != test.workerPool ||
				config.Queues != test.queues || config.OutboundBatchChunk != test.chunk ||
				config.SwapTargetMiB != test.swap || config.SwapPolicy != test.swapPolicy {
				t.Fatalf("config = %#v", config)
			}
			if config.WorkerPoolMaxConns < config.Queues.Total()+2 {
				t.Fatalf("worker pool %d is below queue total %d + 2", config.WorkerPoolMaxConns, config.Queues.Total())
			}
			if postgres := config.RenderPostgreSQL(); postgres != test.postgres {
				t.Fatalf("postgres output = %q, want %q", postgres, test.postgres)
			}
			environment := config.RenderEnvironment()
			for _, forbidden := range []string{"DATABASE_URL", "PASSWORD", "TOKEN", "COOKIE", "SECRET", "WECOM"} {
				if strings.Contains(environment, forbidden) {
					t.Fatalf("environment contains forbidden key %q", forbidden)
				}
			}
		})
	}
}

func TestLookupRejectsNonCanonicalTier(t *testing.T) {
	t.Parallel()
	for _, value := range []string{"", "S", "medium", "m ", "l\n"} {
		if _, err := Lookup(value); !errors.Is(err, ErrInvalidTier) {
			t.Fatalf("Lookup(%q) error = %v", value, err)
		}
	}
}

func TestGenerateIsDeterministicAndSecure(t *testing.T) {
	t.Parallel()
	config, err := Lookup("s")
	if err != nil {
		t.Fatal(err)
	}
	directory := filepath.Join(t.TempDir(), "nested", "generated")
	if err := Generate(config, directory); err != nil {
		t.Fatal(err)
	}
	firstEnvironment := readFile(t, filepath.Join(directory, EnvironmentFileName))
	firstPostgreSQL := readFile(t, filepath.Join(directory, PostgreSQLFileName))
	if err := Generate(config, directory); err != nil {
		t.Fatal(err)
	}
	if got := readFile(t, filepath.Join(directory, EnvironmentFileName)); got != firstEnvironment {
		t.Fatal("environment output changed across consecutive generation")
	}
	if got := readFile(t, filepath.Join(directory, PostgreSQLFileName)); got != firstPostgreSQL {
		t.Fatal("PostgreSQL output changed across consecutive generation")
	}
	assertMode(t, directory, 0o750)
	assertMode(t, filepath.Join(directory, EnvironmentFileName), 0o640)
	assertMode(t, filepath.Join(directory, PostgreSQLFileName), 0o640)
}

func TestGenerateRejectsUnsafeOutputShapes(t *testing.T) {
	t.Parallel()
	config, err := Lookup("m")
	if err != nil {
		t.Fatal(err)
	}
	root := t.TempDir()
	realDirectory := filepath.Join(root, "real")
	if err := os.Mkdir(realDirectory, 0o750); err != nil {
		t.Fatal(err)
	}
	linkedDirectory := filepath.Join(root, "linked")
	if err := os.Symlink(realDirectory, linkedDirectory); err != nil {
		t.Fatal(err)
	}
	if err := Generate(config, linkedDirectory); !errors.Is(err, ErrUnsafeOutputPath) {
		t.Fatalf("symlink directory error = %v", err)
	}

	output := filepath.Join(root, "output")
	if err := Generate(config, output); err != nil {
		t.Fatal(err)
	}
	target := filepath.Join(output, EnvironmentFileName)
	if err := os.Remove(target); err != nil {
		t.Fatal(err)
	}
	outside := filepath.Join(root, "outside")
	if err := os.WriteFile(outside, []byte("unchanged"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(outside, target); err != nil {
		t.Fatal(err)
	}
	if err := Generate(config, output); !errors.Is(err, ErrUnsafeOutputPath) {
		t.Fatalf("symlink target error = %v", err)
	}
	if got := readFile(t, outside); got != "unchanged" {
		t.Fatalf("outside target changed to %q", got)
	}
}

func readFile(t *testing.T, name string) string {
	t.Helper()
	content, err := os.ReadFile(name)
	if err != nil {
		t.Fatal(err)
	}
	return string(content)
}

func assertMode(t *testing.T, name string, want os.FileMode) {
	t.Helper()
	info, err := os.Stat(name)
	if err != nil {
		t.Fatal(err)
	}
	if got := info.Mode().Perm(); got != want {
		t.Fatalf("%s mode = %o, want %o", name, got, want)
	}
}
