CREATE TABLE aicrm_hxc_user_current_v1 (
  hxc_user_id VARCHAR(200) NOT NULL,
  unionid VARCHAR(1024),
  phone VARCHAR(64),
  subscription_tier VARCHAR(100) NOT NULL,
  subscription_expires_at TIMESTAMP NULL,
  monthly_chat_quota INT NOT NULL,
  current_period_used INT NOT NULL,
  consultation_limit INT NOT NULL,
  consultation_used INT NOT NULL,
  sessions_7d BIGINT NOT NULL,
  sessions_30d BIGINT NOT NULL,
  sessions_total BIGINT NOT NULL,
  user_messages_7d BIGINT NOT NULL,
  user_messages_30d BIGINT NOT NULL,
  user_messages_total BIGINT NOT NULL,
  capability_usage JSON NOT NULL,
  last_used_at TIMESTAMP NULL,
  last_capability VARCHAR(100),
  business_stage VARCHAR(100),
  main_line_type VARCHAR(100),
  user_segment VARCHAR(100),
  focus_topics JSON NOT NULL,
  pain_tag VARCHAR(100),
  source_updated_at TIMESTAMP NOT NULL
);
