import React, { useRef, useState } from "react";
import { readCSRFCookie } from "./auth";
import type { HXCSenderConfig } from "./hxc-sender";

export type HXCSenderManagerResult = { readonly status: 200; readonly data: unknown } | { readonly status: 400 | 401 | 403 | 409 | 503; readonly data: unknown };
export interface HXCSenderManagerTransport {
  readonly save: (body: { id: string; sender_userid: string; display_name: string; priority: number; is_active: boolean }, options: RequestInit) => Promise<HXCSenderManagerResult>;
  readonly reorder: (body: { ids: readonly string[] }, options: RequestInit) => Promise<HXCSenderManagerResult>;
  readonly archive: (id: string, options: RequestInit) => Promise<HXCSenderManagerResult>;
  readonly reread: (options: RequestInit) => Promise<{ readonly status: number; readonly data: unknown }>;
}
type Draft = { id: string; sender: string; name: string; priority: string; active: boolean };
const blank = (): Draft => ({ id: "", sender: "", name: "", priority: "0", active: true });
const key = (): string => `hxc-sender-${crypto.getRandomValues(new Uint8Array(18)).join("")}`.slice(0, 128);
const valid = (x: Draft): boolean => x.id.trim() === x.id && x.id.length > 0 && x.id.length <= 200 && x.sender.trim() === x.sender && x.sender.length > 0 && x.sender.length <= 200 && x.name.trim() === x.name && x.name.length <= 200 && Number.isSafeInteger(Number(x.priority)) && Number(x.priority) >= 0 && Number(x.priority) <= 100000;
function status(value: unknown): readonly HXCSenderConfig[] | undefined { if (!Array.isArray(value)) return undefined; return value.every((item) => typeof item === "object" && item !== null && typeof (item as HXCSenderConfig).id === "string") ? value as HXCSenderConfig[] : undefined; }

export function HXCSenderManager({ role, items, transport, readCookie = () => typeof document === "undefined" ? "" : document.cookie, onUnauthenticated, onConfirmed }: { readonly role: "admin" | "ops" | "sales"; readonly items: readonly HXCSenderConfig[]; readonly transport?: HXCSenderManagerTransport; readonly readCookie?: () => string; readonly onUnauthenticated?: () => void; readonly onConfirmed?: (items: readonly HXCSenderConfig[]) => void }): React.ReactElement | null {
  const [draft, setDraft] = useState(blank); const [busy, setBusy] = useState(false); const [unknown, setUnknown] = useState(false); const [notice, setNotice] = useState<string>(); const active = useRef<symbol>();
  if (role !== "admin" || !transport) return null;
  const write = async (run: (csrf: string, idempotencyKey: string) => Promise<HXCSenderManagerResult>) => { if (busy || unknown || active.current) return; const csrf = readCSRFCookie(readCookie()); if (!csrf) { setNotice("安全令牌缺失，未发送本地配置请求。"); return; } const token = Symbol("hxc-write"); active.current = token; setBusy(true); setNotice(undefined); try { const response = await run(csrf, key()); if (active.current !== token) return; if (response.status === 401) { onUnauthenticated?.(); setNotice("登录状态已失效。"); return; } if (response.status === 400 || response.status === 403 || response.status === 409) { setNotice("本地配置未确认，请刷新投影后修正。 "); return; } if (response.status !== 200) { setUnknown(true); setNotice("本地配置结果未知，已锁定以避免重复写入。"); return; } const reread = await transport.reread({ credentials: "same-origin" }); const fresh = reread.status === 200 ? status(reread.data) : undefined; if (!fresh) { setUnknown(true); setNotice("本地配置回读未确认，已锁定以避免重复写入。"); return; } onConfirmed?.(fresh); setDraft(blank()); setNotice("本地发件人配置已回读确认。"); } catch { if (active.current === token) { setUnknown(true); setNotice("本地配置结果未知，已锁定以避免重复写入。"); } } finally { if (active.current === token) { active.current = undefined; setBusy(false); } } };
  const save = () => { if (!valid(draft)) { setNotice("请填写有效的本地配置字段。"); return; } void write((csrf, idempotencyKey) => transport.save({ id: draft.id, sender_userid: draft.sender, display_name: draft.name, priority: Number(draft.priority), is_active: draft.active }, { credentials: "same-origin", headers: { "X-CSRF-Token": csrf, "Idempotency-Key": idempotencyKey } })); };
  const archive = (id: string) => { if (!confirm(`确认归档本地发件人配置 ${id}？`)) return; void write((csrf, idempotencyKey) => transport.archive(id, { credentials: "same-origin", headers: { "X-CSRF-Token": csrf, "Idempotency-Key": idempotencyKey } })); };
  const reorder = (ids: readonly string[]) => void write((csrf, idempotencyKey) => transport.reorder({ ids }, { credentials: "same-origin", headers: { "X-CSRF-Token": csrf, "Idempotency-Key": idempotencyKey } }));
  return <section aria-label="本地发件人管理"><h2>本地发件人管理</h2><p>仅修改本地配置；不会同步企微目录或触发外发。</p>{notice && <p role="status">{notice}</p>}{unknown ? <p role="alert">写入状态待人工确认。</p> : <><form onSubmit={(event) => { event.preventDefault(); save(); }}><input placeholder="配置 ID" value={draft.id} onChange={(e) => setDraft({ ...draft, id: e.currentTarget.value })} disabled={busy}/><input placeholder="本地员工 ID" value={draft.sender} onChange={(e) => setDraft({ ...draft, sender: e.currentTarget.value })} disabled={busy}/><input placeholder="显示名" value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.currentTarget.value })} disabled={busy}/><input value={draft.priority} onChange={(e) => setDraft({ ...draft, priority: e.currentTarget.value })} disabled={busy}/><label><input type="checkbox" checked={draft.active} onChange={(e) => setDraft({ ...draft, active: e.currentTarget.checked })} disabled={busy}/>启用</label><button type="submit" disabled={busy}>保存本地配置</button></form><ul>{items.map((item, index) => <li key={item.id}>{item.senderUserID}（{item.isActive ? "启用" : "停用"}）<button disabled={busy || index === 0} onClick={() => reorder([item.id, ...items.filter((x) => x.id !== item.id).map((x) => x.id)])}>上移</button><button disabled={busy} onClick={() => archive(item.id)}>归档</button></li>)}</ul></>}</section>;
}
