// Survey's public screen has no default fetch implementation: the generated
// carrier injects a same-origin transport after contract wiring. Result tokens
// are held only in this closure and are never placed in URL, DOM, or storage.
export type PublicDefinition = { id:number; slug:string; title:string; description:string; answer_display_mode:"all_in_one"|"one_by_one"; version:number; questions:Array<{id:number;type:"single_choice"|"multi_choice";title:string;required:boolean;sort_order:number;minimum_selections:number;maximum_selections:number;options:Array<{id:number;option_text:string;sort_order:number}>}> }
export type PublicAnswer = { question_id:number; option_ids:number[] }
export type SubmissionResult = { submission_id:number; definition_version:number; submitted_at:string; local_only:true; external_executed:false }
export interface PublicSurveyTransport { definition(slug:string):Promise<PublicDefinition>; submit(slug:string,input:{version:number;submission_key:string;answers:PublicAnswer[]}):Promise<{receipt:unknown;result_token:string}>; result(resultToken:string):Promise<SubmissionResult> }
export function publicSlug(pathname:string):string|null { const m=/^\/q\/([a-z0-9][a-z0-9-]{0,119})$/.exec(pathname);return m?m[1]:null }
export function createPublicSurveyController(transport:PublicSurveyTransport,pathname:string){ const slug=publicSlug(pathname);let token:string|undefined;return {slug, async load(){if(!slug)throw new Error("invalid public survey path");return transport.definition(slug)}, async submit(input:{version:number;submission_key:string;answers:PublicAnswer[]}){if(!slug)throw new Error("invalid public survey path");const response=await transport.submit(slug,input);token=response.result_token;return response.receipt}, async result(){if(!token)throw new Error("no accepted public submission");return transport.result(token)} } }
export function createPublicSubmissionFlight(makeKey:()=>string) { let key:string|undefined; let active:Promise<unknown>|undefined; let unknown=false; return { submit<T>(run:(submissionKey:string)=>Promise<T>):Promise<T> { if (unknown) return Promise.reject(new Error("submission status unknown")); if (active) return active as Promise<T>; key ??= makeKey(); active=run(key).catch((error)=>{unknown=true;throw error}); return active as Promise<T> }, get submissionKey(){return key}, get unknown(){return unknown} } }
